service: aws-image-analyzer-rekognito

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    shouldStartNameWithService: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - rekognition:*
      Resource: '*'
    - Effect: Allow
      Action:
        - translate:TranslateText
      Resource: '*'


functions:
  analyze:
    handler: handler.analyze
    events:
      - http:
          path: /analyze
          method: get
